### ISSUE TITLE
Create a File

### ISSUE THREAD

**Issue by Jose3212** [estatic/pydatalake-gen2#2]
Hi!

First thanks for the development of this library. But now I want to create a file inside one folder of my filesystem. I have tried first using create_path which works fine, but then I try append and after that flush with the function update_path. But the file is still empty, what is the correct way to créate a file and add content to it?

**Comment by estatic** [comment]
Hi @Jose3212 let me investigate the problem, I will try to find a solution

**Comment by estatic** [comment]
Hi @Jose3212 ,

After some investigation, I found the solution.
So, here is an example:

path = self.client.create_path('test1', 'test/test_file3', resource='file')
response = self.client.update_path('test1', 'test/test_file3', 'append', 'test123123123123123123123123', position=0)
response = self.client.update_path('test1', 'test/test_file3', 'append', 'test435345634563456345634565', position=28)
response = self.client.update_path('test1', 'test/test_file3', 'append', 'test908790879870908908908908', position=56)
response = self.client.update_path('test1', 'test/test_file3', 'flush', position=84)


The meaning of the code is: When you are appending data to the file, you must set **position** variable which is position you would to save from.

When you are flushing file, you must set by what position you would like to save your file.

**Comment by Jose3212** [comment]
It Works thank you! I hope I can contribute soon.

I have another cuestion with the read option:

when I invoke read_path to open the file I have just write it I have this error:
```
    data = self.client.read_path(filesystem=self.filesystem, path=path)
.venv/lib/python3.6/site-packages/azure/datalake/gen2/client.py:433: in read_path
    response = self.make_request("GET", f"https://{self.storage_account}.{self.dns_suffix}/"
.venv/lib/python3.6/site-packages/azure/datalake/gen2/client.py:124: in make_request
    data=data)
.venv/lib/python3.6/site-packages/requests/api.py:60: in request
    return session.request(method=method, url=url, **kwargs)
.venv/lib/python3.6/site-packages/requests/sessions.py:519: in request
    prep = self.prepare_request(req)
.venv/lib/python3.6/site-packages/requests/sessions.py:462: in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
.venv/lib/python3.6/site-packages/requests/models.py:317: in prepare
    self.prepare_auth(auth, url)
.venv/lib/python3.6/site-packages/requests/models.py:548: in prepare_auth
    r = auth(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <azure.datalake.gen2.client.SharedKeyAuth object at 0x7fcb7d3cfc88>, r = <PreparedRequest [GET]>

    def __call__(self, r: Request):
        print(f"Requesting... {r.url}")

        required_headers = {}
        for key, val in r.headers.items():
            if key in ["Content-Length", "Content-Type"] or key.startswith("x-ms"):
                required_headers[key] = val
        r.headers = OrderedDict(required_headers)
        r.headers["x-ms-date"] = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")
        r.headers["x-ms-version"] = "2018-11-09"

        parsed_url = urlparse(r.url)
        qparams = parsed_url.query.split("&")
        params = {}
        for param in qparams:
>           key = param[:param.index("=")]
E           ValueError: substring not found

.venv/lib/python3.6/site-packages/azure/datalake/gen2/client.py:63: ValueError
```

The filesystem param I give it in the invoke inside the function, I have it stored inside the class we `self.client.read_path(filesystem=self.filesystem, path=path)
` use and the path param is one string we give it in the test function. I hope that after that I will be able to at least contribute with a README.md

**Comment by estatic** [comment]
I have uploaded fix for your problem. But I'm getting Auth error which I don't know yet how to fix. I have the same problem for few methods and didn't find an answer how to resolve it
