### ISSUE TITLE
Unable to read file

### ISSUE THREAD

**Issue by saurabbhsp** [estatic/pydatalake-gen2#8]
Hi,
Kudos for writing this API. The current way to access the data lake store gen-2 using blobstore api is not so good.

I am getting this error while reading a file for data lake store.
403: {"error":{"code":"AuthenticationFailed","message":"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature

Strange part is that I am able to create and rename a file, however reading the files fails. Not sure if the Rest API itself is broken, which I think is one possibility.

**Comment by estatic** [comment]
Hi, Could you please send to me an example of how are you using the API (I mean which of variables are you giving to the method)? Also, could you let me know the library version you are using?

**Comment by saurabbhsp** [comment]
I am using pydatalake-gen2==0.0.9.
I am calling following code block

`client.read_path("storage", "staging/Ne00008K10/test.txt")`
storage is the filesystem and test.txt is the filename

**Comment by estatic** [comment]
Got it, let me check, will reply to you in few hours

**Comment by estatic** [comment]
Hi, could you please update your version to 0.0.10? Thanks!

**Comment by saurabbhsp** [comment]
Sure, let me update and try again

**Comment by saurabbhsp** [comment]
Thanks, now its working properly.
